config/routes.rb
Rails.application.routes.draw do
  resources :gantts, only: [:index] do
    collection do
      get  :data, as: 'data'
      post :db_action, :as => "db_action"
    end
  end

  root to: 'gantts#index'
end

app/models/concerns/gantable.rb
module Gantable
  def self.included(base)
    base.extend(ClassMethods)
    base.class_eval do
      has_many :sources, as: :sourceable, class_name: 'GanttLink'
      has_many :targets, as: :targetable, class_name: 'GanttLink'

      before_destroy :destroy_gantt_links  
    end
  end

  def destroy_gantt_links
    self.sources.destroy_all
    self.targets.destroy_all
  end  

  module ClassMethods
  end
end

app/models/gantt_link.rb
class GanttLink < ActiveRecord::Base
  belongs_to :project  
  belongs_to :sourceable, polymorphic: true  
  belongs_to :targetable, polymorphic: true

  validates_presence_of :project
  validates_presence_of :targetable
  validates_presence_of :sourceable

  def from_params(params, session, id)
    source_addr = params["#{id}_source"]
    source = if (temp = session["custom-#{source_addr}"])
      temp['type'] + "-" + temp['id'].to_s
    else
      source_addr
    end

    source_type = source.split('-')[0].classify.constantize
    source_id   = source.split('-')[1].to_i

    target_addr = params["#{id}_target"]
    target = if (temp=session["custom-#{target_addr}"])
      temp['type'] + "-" + temp['id'].to_s
    else
      target_addr
    end

    target_type = target.split('-')[0].classify.constantize
    target_id   = target.split('-')[1].to_i


    self.sourceable = source_type.find(source_id)
    self.targetable = target_type.find(target_id)
    self.gtype      = params["#{id}_type"]
    # inherit project scope
    self.project_id = self.targetable.instance_of?(Project) ? self.targetable.id : self.targetable.project_id 
  end  
end

app/models/project.rb
class Project < ActiveRecord::Base
  include Gantable

  has_many :tasks
  has_many :ganttlinks 

  def from_params(params, id)
    self.name = params["#{id}_text"].to_s
  end  
end

app/models/task.rb
class Task < ActiveRecord::Base
  include Gantable

  belongs_to :project

  # Below Rails 4
  # scope :gantt_data, where("start_date IS NOT NULL AND duration IS NOT NULL").joins(:project)
  # Rails 4 and above
  scope :gantt_data, -> { where.not(start_date: nil, duration: nil).order(:sortorder).joins(:project) }

  def reorder(target)
    source_row = self
    target_row = Task.find(target)
    from = Task.gantt_data.index(source_row)
    to   = Task.gantt_data.index(target_row)
    if from < to
      effected = Task.gantt_data[from..to]
    else
      effected = Task.gantt_data[to..from]
    end
  end

  def from_params(params, id)
    self.name       = params["#{id}_text"].to_s
    self.start_date = params["#{id}_start_date"].to_date
    self.duration   = params["#{id}_duration"].to_i
    self.progress   = params["#{id}_progress"].to_f
    self.parent     = params["#{id}_parent"].split('-')[1].to_i  
    self.project_id = self.parent # this is limitation
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/gantts_controller.rb
class GanttsController < ApplicationController

  def index
  end


  def data
    # you can simple limit chart to your one project like this
    # tasks = Task.gantt_data.where(project_id: your_project)
    tasks    = Task.gantt_data
    projects = tasks.select("projects.id, projects.name").uniq
    links    = GanttLink.all

    render json: {
      data: (projects.map do |project| 
        {
          id: "projects-#{project.id}",
          text: project.name,
          type: 'project',
          open: true
        }
      end) + tasks.map do |task|
        {
          id: "tasks-#{task.id}",
          text: task.name,
          start_date: task.start_date,
          duration: task.duration,
          progress: task.progress,
          sortorder: task.sortorder,
          parent: "projects-#{task.project_id}",
          type: 'task'
        }
      end,

      links: links.map do |link|
      {
        id: "links-#{link.id}",
        source: "#{link.sourceable_type.to_s.pluralize.downcase}-#{link.sourceable.id}", 
        target: "#{link.targetable_type.to_s.pluralize.downcase}-#{link.targetable.id}", 
        type: link.gtype
      }  
      end
    }, status: :ok
  end

 def db_action
    params['ids'].split(',').each do |id|
      @id   = id

      @mode = params["#{@id}_!nativeeditor_status"]          
      # project looks like a task but we need the project to be the project
      if session["custom-#{id}"]
        @gantt_mode = session["custom-#{id}"]['type'] 
        db_id = session["custom-#{id}"]['id']
      else
        # project update and delete look like a task but we need the project to be the project
        @gantt_mode = if @mode=='inserted' then params['gantt_mode'] else @id.split('-')[0] end
        db_id = @id.split('-')[1].to_i
      end

      case @gantt_mode
      when "tasks"
        case @mode
        when "inserted"
          task = Task.new
          task.from_params(params, @id)            
          if task.save
            session["custom-#{@id}"] = { id: task.id, type: @gantt_mode }
            @tid = @id
          end

        when "deleted"
          task = Task.find(db_id)
          task.destroy
          @tid= @id

        when "updated"
          task = Task.find(db_id)
          task.from_params(params, @id)            
          if task.save
            @tid = @id
          end

        when "order"
          task = Task.find(db_id)
          task.reorder(params["tasks-#{task.id}_target"].split('-')[1].to_i)
        end              


      when "links"
        case @mode
        when "inserted"
            link = GanttLink.new
            link.from_params(params, session, @id)
            if link.save
              session["custom-#{@id}"] = { id: link.id, type: @gantt_mode }
              @tid = @id
            end

        when "deleted"
            link = GanttLink.find(db_id)
            link.destroy
            @tid = @id           

        when "updated"
            link = GanttLink.find(db_id)
            link.from_params(params, session, @id)
            if link.save
              @tid = @id
            end
        end        


      when "projects"
        case @mode
        when "deleted"
            project = Project.find(db_id)                  
            project.destroy
            @tid = @id

        when "updated"
            project = Project.find(db_id)
            project.from_params(params, @id)
            if project.save
              @tid = @id
            end
        end              
      end
    end
  end 

end

app/views/gantts/db_action.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<data>
    <action type="<%= @mode %>" sid="<%= @id %>" tid="<%= @tid %>" />
</data>

app/views/gantts/index.html.erb
<%= stylesheet_link_tag "dhtmlxgantt", :media => "all" %>
<%= stylesheet_link_tag "skins/dhtmlxgantt_skyblue", :media=> "all" %>

<%= javascript_include_tag "dhtmlxgantt" %>
<%= javascript_include_tag "locale/locale" %>

<%= javascript_include_tag "ext/dhtmlxgantt_marker" %>
<%= javascript_include_tag "ext/dhtmlxgantt_quick_info" %>
<%= javascript_include_tag "ext/dhtmlxgantt_tooltip" %>
<%= javascript_include_tag "ext/dhtmlxgantt_expand.js" %>

<style type="text/css">
  html, body{ height:100%; padding:0px; margin:0px; overflow: hidden;}
</style>

<style>
  div[task_id^='tasks-'] .gantt_add, .gantt_grid_head_add {
    display: none !important;
  }
  .dhx_expand_icon {
    position:absolute;
    top:0px;
    right:0px;
    background-image:url(data:image/gif;base64,R0lGODlhEgAkANUmAAAAAIqWpo+croyYqpKfs1xqfpiox3qJooqZtWt5kFBebwUFBpWjuQYGB3B7kWt1ipyrxKOy0Ki52aa21Zinv5+uylFZahQWGicrMmNtgAsNDzE2QB0gJjxCTjc8Rg8RExseIlJbakZMWSksM1tjdkdOXMLV/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACYALAAAAAASACQAAAbhQJNwSCwaj8ikcsFsOp8LoSZArVqrAI3wMuh6v4BB+CLkCM7oNABw5ggxhLh8vgYQMEIAQ8/f+xmAG0IdCoWGhwAUih15BY6PkBCSECVCFgmYmZoAFZ0WeQehoqMRpREkQhkIq6ytABOwGXkGtLW2ErgSD0IOAL2/vsEOww5KxsfIycrLeSYAztDP0tDOV9ZVRF/a2s/Oad/fRHPj490ADejp6g2ADEMXh/EKH4oU5pD4BSCTQxua/wlGdKpgbpTBAx5MDbHQqiECEbAmmLNF0UCIXEMeANDIcaPHaMxCCgkCADs=);
    width:18px;
    height:18px;
    cursor:pointer;
    background-position:0px 18px;
    z-index:16;
  }  
</style>

<div id="gantt_here" style='width:100%; height:100%;'></div>

<script type="text/javascript">
  // Add today marker
  var today = new Date();
  var date_to_str = gantt.date.date_to_str(gantt.config.task_date);
  gantt.addMarker({
    start_date: today,
    css: "today",
    text: "Today",
    title: "Today: " + date_to_str(today)
  });

  gantt.config.xml_date = "%Y-%m-%d %H:%i:%s";
  gantt.config.order_branch = true;
  gantt.init("gantt_here");
  gantt.load("<%= data_gantts_path %>", "json");
  var dp = new dataProcessor("<%= db_action_gantts_path %>");
  dp.init(gantt);
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dhtmlx Gantt RubyOnRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>